# Generated by Django 4.1.7 on 2023-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('cedula', models.TextField()),
                ('usuario', models.TextField()),
                ('contrasena', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
