# Generated by Django 4.1.7 on 2023-03-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_propietario_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('cedula', models.TextField()),
                ('cliente', models.TextField()),
                ('servicio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contrato_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('numero_contrato', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('estado_descripcion', models.TextField()),
                ('estado_vigencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('direccion', models.TextField()),
                ('referencia', models.TextField()),
                ('altitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
            ],
        ),
        migrations.CreateModel(
            name='plan_velocidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('descripcion', models.TextField()),
                ('velocidad', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
            ],
        ),
        migrations.CreateModel(
            name='telefono_localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('telefono', models.TextField()),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
                ('codigo_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TimeField()),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
                ('codigo_plan_velocidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.plan_velocidad')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('local', models.TextField()),
                ('punto', models.TextField()),
                ('numero', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=4)),
                ('observacion', models.TextField()),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.cliente')),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
            ],
        ),
        migrations.CreateModel(
            name='corresponsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('codigo_corresponsales', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('codigo_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.localidad')),
                ('codigo_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='contrato_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_detalle', models.TextField()),
                ('codigo_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.contrato_cabecera')),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.producto')),
            ],
        ),
        migrations.CreateModel(
            name='cobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('adjunto_foto', models.ImageField(upload_to='')),
                ('fecha_anulacion', models.DateField()),
                ('codigo_corresponsales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.corresponsales')),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado')),
                ('codigo_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.factura')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.estado'),
        ),
    ]
