# Generated by Django 4.1.7 on 2023-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_cliente_contrato_cabecera_estado_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='punto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='cedula',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
