# Generated by Django 4.1.7 on 2023-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0006_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_cabecera',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contrato_cabecera',
            name='numero_contrato',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contrato_detalle',
            name='codigo_detalle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado_vigencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plan_velocidad',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='telefono_localidad',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='telefono_localidad',
            name='telefono',
            field=models.CharField(max_length=255),
        ),
    ]
